# Generated by Django 5.0.7 on 2024-09-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_remove_investment_investment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentplan",
            name="planned_expense",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.expenseplan",
                verbose_name="Planned Expense",
            ),
        ),
    ]
